apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-deployment pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi