apiVersion: v1
kind: Secret
metadata:
   name: backend-secret
data:
   MONGODB_URI: "bW9uZ29kYitzcnY6Ly9hbXdhdToxMjM0YW5uQGNsdXN0ZXIwLmhuZzFzbDgubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ=="